import base64
import io
import logging
import os
from typing import Optional

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/pipeline")

# Lazy-load rembg session to avoid slow startup
_rembg_session = None


def get_rembg_session():
    global _rembg_session
    if _rembg_session is None:
        try:
            from rembg import new_session
            # isnet-general-use is much better for general objects (toys, animals, etc.)
            # u2net is biased toward human/salient objects
            _rembg_session = new_session("isnet-general-use")
            logger.info("rembg session initialized with isnet-general-use model")
        except ImportError:
            logger.error("rembg not installed. Run: pip install 'rembg[cpu]'")
            raise HTTPException(status_code=500, detail="rembg not installed")
    return _rembg_session


class RemoveBackgroundRequest(BaseModel):
    image: str  # base64 encoded JPEG/PNG


class RemoveBackgroundResponse(BaseModel):
    image: str  # base64 encoded PNG with transparent background
    success: bool


class GenerateBackgroundRequest(BaseModel):
    prompt: str
    style: Optional[str] = "3D animated children's movie"


class GenerateBackgroundResponse(BaseModel):
    image: str  # base64 encoded PNG
    success: bool


@router.post("/remove-background")
async def remove_background(request: RemoveBackgroundRequest):
    try:
        from rembg import remove
        from PIL import Image, ImageFilter

        image_data = base64.b64decode(request.image)
        input_image = Image.open(io.BytesIO(image_data)).convert("RGBA")

        # Upscale small images for better segmentation
        w, h = input_image.size
        min_dim = min(w, h)
        if min_dim < 512:
            scale = 512 / min_dim
            input_image = input_image.resize(
                (int(w * scale), int(h * scale)), Image.LANCZOS
            )

        session = get_rembg_session()
        output_image = remove(
            input_image,
            session=session,
            alpha_matting=True,
            alpha_matting_foreground_threshold=240,
            alpha_matting_background_threshold=10,
            alpha_matting_erode_size=10,
        )

        # Smooth the alpha edges slightly to avoid harsh cutouts
        alpha = output_image.split()[3]
        alpha = alpha.filter(ImageFilter.GaussianBlur(radius=1))
        output_image.putalpha(alpha)

        output_buffer = io.BytesIO()
        output_image.save(output_buffer, format="PNG", optimize=True)
        output_base64 = base64.b64encode(output_buffer.getvalue()).decode("utf-8")

        return RemoveBackgroundResponse(image=output_base64, success=True)
    except ImportError:
        raise HTTPException(
            status_code=500,
            detail="rembg not installed. Run: pip install 'rembg[cpu]' Pillow",
        )
    except Exception as e:
        logger.error(f"Background removal error: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/generate-background")
async def generate_background(request: GenerateBackgroundRequest):
    try:
        import google.genai as genai
        from google.genai import types

        project_id = os.getenv("PROJECT_ID")
        location = os.getenv("LOCATION", "us-central1")

        client = genai.Client(vertexai=True, project=project_id, location=location)

        full_prompt = (
            f"{request.prompt}. "
            f"Style: {request.style}. "
            "Vibrant colors, child-friendly, no text, no people, "
            "wide angle establishing shot, suitable as a background for animation."
        )

        response = client.models.generate_images(
            model="imagen-3.0-generate-002",
            prompt=full_prompt,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                aspect_ratio="16:9",
                safety_filter_level="BLOCK_MEDIUM_AND_ABOVE",
            ),
        )

        if response.generated_images and len(response.generated_images) > 0:
            image_bytes = response.generated_images[0].image.image_bytes
            image_base64 = base64.b64encode(image_bytes).decode("utf-8")
            return GenerateBackgroundResponse(image=image_base64, success=True)
        else:
            raise HTTPException(
                status_code=500, detail="No image generated by Imagen"
            )

    except Exception as e:
        logger.error(f"Background generation error: {e}")
        # Fallback: generate a gradient placeholder using Pillow
        try:
            from PIL import Image, ImageDraw

            img = Image.new("RGB", (1280, 720))
            draw = ImageDraw.Draw(img)
            prompt_lower = request.prompt.lower()
            if any(w in prompt_lower for w in ["jungle", "forest"]):
                colors = [(34, 139, 34), (0, 100, 0)]
            elif any(w in prompt_lower for w in ["ocean", "sea", "water"]):
                colors = [(0, 105, 148), (0, 191, 255)]
            elif any(w in prompt_lower for w in ["space", "galaxy"]):
                colors = [(10, 10, 40), (75, 0, 130)]
            elif any(w in prompt_lower for w in ["desert", "sand"]):
                colors = [(237, 201, 175), (194, 148, 67)]
            elif any(w in prompt_lower for w in ["castle", "palace"]):
                colors = [(105, 105, 105), (192, 192, 192)]
            elif any(w in prompt_lower for w in ["ice", "snow", "frozen"]):
                colors = [(173, 216, 230), (240, 248, 255)]
            elif any(w in prompt_lower for w in ["volcano", "lava", "fire"]):
                colors = [(178, 34, 34), (255, 140, 0)]
            elif any(w in prompt_lower for w in ["savanna", "africa", "grassland"]):
                colors = [(218, 165, 32), (107, 142, 35)]
            else:
                colors = [(135, 206, 235), (34, 139, 34)]

            for y in range(720):
                r = int(colors[0][0] + (colors[1][0] - colors[0][0]) * y / 720)
                g = int(colors[0][1] + (colors[1][1] - colors[0][1]) * y / 720)
                b = int(colors[0][2] + (colors[1][2] - colors[0][2]) * y / 720)
                draw.line([(0, y), (1280, y)], fill=(r, g, b))

            output_buffer = io.BytesIO()
            img.save(output_buffer, format="PNG")
            image_base64 = base64.b64encode(output_buffer.getvalue()).decode(
                "utf-8"
            )
            logger.warning(f"Imagen failed ({e}), using gradient fallback")
            return GenerateBackgroundResponse(image=image_base64, success=True)
        except Exception as fallback_err:
            logger.error(f"Fallback also failed: {fallback_err}")
            raise HTTPException(
                status_code=500, detail=f"Image generation failed: {e}"
            )
